services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:3000:3000'
    container_name: backend
    env_file:
      - ./backend/.env
    restart: unless-stopped
