services:
  frontend:
    build:
      context: ./frontend/maksymilian.dev
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    env_file:
      - ./frontend/maksymilian.dev/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
